
chunk             ::= stmt* EOF

stmt              ::= expr ";"

expr              ::= mul_expr ( ( "+" | "-" ) mul_expr )*

mul_expr          ::= unary_expr ( ( "*" | "/" | "%" ) unary_expr )*

unary_expr        ::= "-" unary_expr | prim_expr

prim_expr         ::= "nil" | NUMBER | "(" expr ")"
